<a href="https://colab.research.google.com/github/AleksandrRevuka/HW_Data_Science/blob/main/HW_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [1]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(a)


[ 1  2  3  4  5  6  7  8  9 10]


Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [2]:
m = np.zeros((3, 3), dtype=int)

print(m)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [3]:
m_1 = np.random.randint(1, 11, size=(5, 5))

print(m_1)

[[ 8  1  6  3  8]
 [ 9  2  6  7  8]
 [ 8 10  8  6  9]
 [ 6  6  3 10  7]
 [ 2  1 10  4 10]]


Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [4]:
m_2 = np.random.random((4, 4))

print(m_2)

[[0.50894793 0.88726405 0.15734538 0.80338865]
 [0.89370761 0.30589616 0.65134316 0.30095721]
 [0.83985959 0.53941823 0.31056453 0.78239061]
 [0.57283423 0.44321811 0.00527266 0.47466659]]


Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [5]:
m_3 = np.random.randint(1, 11, size=(1, 5))
m_4 = np.random.randint(1, 11, size=(1, 5))

print(f"Addition result: {m_3 + m_4}")
print(f"Subtraction result: {m_3 - m_4}")
print(f"Multiplication result: {m_3 * m_4}")

Addition result: [[13 12  7 15 13]]
Subtraction result: [[-3  8 -1  5  7]]
Multiplication result: [[40 20 12 50 30]]


Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [6]:
v_1 = np.array([1, 2, 3, 4, 5, 6, 7])
v_2 = np.array([7, 6, 5, 4, 3, 2, 1])

print(f"Scalar product of vectors: {np.dot(v_1, v_2)}")

Scalar product of vectors: 84


Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [7]:
m_5 = np.random.randint(1, 11, size=(2, 2))
m_6 = np.random.randint(1, 11, size=(2, 3))

print(m_5,"\n")
print(m_6,"\n")

print(f"Multiplication of matrices:\n{np.dot(m_5, m_6)}")

[[4 3]
 [1 4]] 

[[ 2  6  6]
 [10 10  8]] 

Multiplication of matrices:
[[38 54 48]
 [42 46 38]]


Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [8]:
m_7 = np.random.randint(1, 11, size=(3, 3))

print(f"Inverse matrix:\n{np.linalg.inv(m_7)}")

Inverse matrix:
[[-0.07142857  0.03061224  0.14285714]
 [-0.28571429  0.55102041 -0.42857143]
 [ 0.35714286 -0.43877551  0.28571429]]


Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [9]:
print(f"Matrix:\n{m_2}\n")
print(f"Transposition matrix:\n{m_2.T}")

Matrix:
[[0.50894793 0.88726405 0.15734538 0.80338865]
 [0.89370761 0.30589616 0.65134316 0.30095721]
 [0.83985959 0.53941823 0.31056453 0.78239061]
 [0.57283423 0.44321811 0.00527266 0.47466659]]

Transposition matrix:
[[0.50894793 0.89370761 0.83985959 0.57283423]
 [0.88726405 0.30589616 0.53941823 0.44321811]
 [0.15734538 0.65134316 0.31056453 0.00527266]
 [0.80338865 0.30095721 0.78239061 0.47466659]]


Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [10]:
m_8 = np.array([[0, 2, 3, 1],
                [5, 1, 5, 3],
                [9, 1, 10, 2]])

v_3 = np.array([5, 6, 7, 8])

print(f"The result of multiplying a matrix by a vector:{np.dot(m_8, v_3)}")

The result of multiplying a matrix by a vector:[ 41  90 137]


Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [11]:
m_9 = np.random.random((2, 3))
v_4 = np.random.random(3)

print(m_9, "\n")
print(v_4, "\n")

print(f"The result of multiplying a matrix by a vector:\n{np.dot(m_9, v_4)}")

[[0.51498806 0.40098738 0.66905856]
 [0.67157018 0.92789138 0.5831425 ]] 

[0.97575825 0.64230945 0.03076827] 

The result of multiplying a matrix by a vector:
[0.78064761 1.26922583]


Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [12]:
m_10 = np.random.randint(1, 11, size=(2, 2))
m_11 = np.random.randint(1, 11, size=(2, 2))

print(m_10, "\n")
print(m_11, "\n")

print(f"Multiplication of matrices:\n{m_10 * m_11}")

[[ 1  5]
 [ 1 10]] 

[[10  4]
 [ 3  7]] 

Multiplication of matrices:
[[10 20]
 [ 3 70]]


Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [13]:
print(m_10, "\n")
print(m_11, "\n")

print(f"Multiplication of matrices:\n{np.dot(m_10, m_11)}")

[[ 1  5]
 [ 1 10]] 

[[10  4]
 [ 3  7]] 

Multiplication of matrices:
[[25 39]
 [40 74]]


Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [14]:
m_12 = np.random.randint(1, 100, size=(5, 5))

print(m_12, "\n")

print(sum(map(sum, m_12)))
print(m_12.sum())

[[16 76 60 64 61]
 [42 51  5 68 62]
 [88 61 94 33 16]
 [52 49 92 71 78]
 [ 6 49 19  3 35]] 

1251
1251


Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [15]:
m_13 = np.random.randint(1, 11, size=(4, 4))
m_14 = np.random.randint(1, 11, size=(4, 4))

print(m_13, "\n")
print(m_14, "\n")

print(f"Matrix difference:\n{m_13 - m_14}")

[[ 9  8  5  2]
 [10  4  6  9]
 [ 5  2  2  1]
 [ 2  5  6  4]] 

[[ 6  9  6  4]
 [ 9  5  1  9]
 [ 7  8  6 10]
 [ 2  5  1  8]] 

Matrix difference:
[[ 3 -1 -1 -2]
 [ 1 -1  5  0]
 [-2 -6 -4 -9]
 [ 0  0  5 -4]]


Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.



In [16]:
m_15 = np.random.random((3, 3))

column_vector = np.zeros((3, 1))

for i, el in enumerate(m_15):
  column_vector[i, 0] = el.sum()

print(m_15, "\n")
print(column_vector)

[[0.54138693 0.99879912 0.94869155]
 [0.3121838  0.1236744  0.34623323]
 [0.41320589 0.77178395 0.21000297]] 

[[2.48887759]
 [0.78209143]
 [1.39499281]]


Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [17]:
print(f"matrix of numbers:\n{m_8}\n")

print(f"matrix of squares of numbers:\n{m_8 * m_8}")

matrix of numbers:
[[ 0  2  3  1]
 [ 5  1  5  3]
 [ 9  1 10  2]]

matrix of squares of numbers:
[[  0   4   9   1]
 [ 25   1  25   9]
 [ 81   1 100   4]]


Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [18]:
v_5 = np.random.randint(1, 51, size=(4))
print(v_5, "\n")

print(f"Square root:\n{np.sqrt(v_5)}")

[10 21 41 40] 

Square root:
[3.16227766 4.58257569 6.40312424 6.32455532]
