<a href="https://colab.research.google.com/github/AleksandrRevuka/HW_Data_Science/blob/main/HW_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [6]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(a)


[ 1  2  3  4  5  6  7  8  9 10]


Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [10]:
m = np.zeros((3, 3), dtype=int)

print(m)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [13]:
m_1 = np.random.randint(1, 11, size=(5, 5))

print(m_1)

[[10  9  1  3  6]
 [ 4  2  9  1  9]
 [ 7  9 10  7  2]
 [ 9  5  1  2  5]
 [ 5  1  1  8  5]]


Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [15]:
m_2 = np.random.random((4, 4))

print(m_2)

[[0.94094113 0.28604582 0.01063749 0.17169309]
 [0.29682591 0.36041051 0.40499739 0.45340652]
 [0.13207395 0.85520983 0.4749625  0.40626975]
 [0.52083773 0.50970157 0.20166025 0.11911295]]


Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [28]:
m_3 = np.random.randint(1, 11, size=(1, 5))
m_4 = np.random.randint(1, 11, size=(1, 5))

print(f"Addition result: {m_3 + m_4}")
print(f"Subtraction result: {m_3 - m_4}")
print(f"Multiplication result: {m_3 * m_4}")

Addition result: [[ 5 14 15 10 18]]
Subtraction result: [[-1  6 -3  8  2]]
Multiplication result: [[ 6 40 54  9 80]]


Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [31]:
v_1 = np.array([1, 2, 3, 4, 5, 6, 7])
v_2 = np.array([7, 6, 5, 4, 3, 2, 1])

print(f"Scalar product of vectors: {np.dot(v_1, v_2)}")

Scalar product of vectors: 84


Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [62]:
m_5 = np.random.randint(1, 11, size=(2, 2))
m_6 = np.random.randint(1, 11, size=(2, 3))

print(m_5,"\n")
print(m_6,"\n")

print(f"Multiplication of matrices:\n{np.dot(m_5, m_6)}")

[[1 9]
 [6 6]] 

[[ 6  4  8]
 [ 6 10 10]] 

Multiplication of matrices:
[[ 60  94  98]
 [ 72  84 108]]


Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [37]:
m_7 = np.random.randint(1, 11, size=(3, 3))

print(f"Inverse matrix:\n{np.linalg.inv(m_7)}")

Inverse matrix:
[[ 0.23148148 -0.21296296  0.10185185]
 [-0.14814815  0.2962963  -0.18518519]
 [-0.19444444  0.13888889  0.19444444]]


Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [44]:
print(f"Matrix:\n{m_2}\n")
print(f"Transposition matrix:\n{m_2.T}")

Matrix:
[[0.94094113 0.28604582 0.01063749 0.17169309]
 [0.29682591 0.36041051 0.40499739 0.45340652]
 [0.13207395 0.85520983 0.4749625  0.40626975]
 [0.52083773 0.50970157 0.20166025 0.11911295]]

Transposition matrix:
[[0.94094113 0.29682591 0.13207395 0.52083773]
 [0.28604582 0.36041051 0.85520983 0.50970157]
 [0.01063749 0.40499739 0.4749625  0.20166025]
 [0.17169309 0.45340652 0.40626975 0.11911295]]


Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [54]:
m_8 = np.array([[0, 2, 3, 1],
                [5, 1, 5, 3],
                [9, 1, 10, 2]])

v_3 = np.array([5, 6, 7, 8])

print(f"The result of multiplying a matrix by a vector:{np.dot(m_8, v_3)}")

The result of multiplying a matrix by a vector:[ 41  90 137]


Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [57]:
m_9 = np.random.random((2, 3))
v_4 = np.random.random(3)

print(m_9, "\n")
print(v_4, "\n")

print(f"The result of multiplying a matrix by a vector:\n{np.dot(m_9, v_4)}")

[[0.76267857 0.92161355 0.18706407]
 [0.18486862 0.70798944 0.70047301]] 

[0.75197285 0.65600171 0.90888061] 

The result of multiplying a matrix by a vector:
[1.34811255 1.2401048 ]


Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [64]:
m_10 = np.random.randint(1, 11, size=(2, 2))
m_11 = np.random.randint(1, 11, size=(2, 2))

print(m_10, "\n")
print(m_11, "\n")

print(f"Multiplication of matrices:\n{m_10 * m_11}")

[[7 8]
 [6 4]] 

[[4 2]
 [3 3]] 

Multiplication of matrices:
[[28 16]
 [18 12]]


Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [66]:
print(m_10, "\n")
print(m_11, "\n")

print(f"Multiplication of matrices:\n{np.dot(m_10, m_11)}")

[[7 8]
 [6 4]] 

[[4 2]
 [3 3]] 

Multiplication of matrices:
[[52 38]
 [36 24]]


Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [72]:
m_12 = np.random.randint(1, 100, size=(5, 5))

print(m_12, "\n")

print(sum(map(sum, m_12)))
print(m_12.sum())

[[87 45 37 87 84]
 [87 99  7 16 80]
 [47  5 64 37 94]
 [65 79 15  2 91]
 [69 27 77 46  6]] 

1353
1353


Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [74]:
m_13 = np.random.randint(1, 11, size=(4, 4))
m_14 = np.random.randint(1, 11, size=(4, 4))

print(m_13, "\n")
print(m_14, "\n")

print(f"Matrix difference:\n{m_13 - m_14}")

[[3 9 6 4]
 [7 3 4 5]
 [6 8 4 1]
 [2 1 2 4]] 

[[ 4  2  6  9]
 [ 8  6  5  7]
 [ 4  8  1 10]
 [ 1  1  5  5]] 

Matrix difference:
[[-1  7  0 -5]
 [-1 -3 -1 -2]
 [ 2  0  3 -9]
 [ 1  0 -3 -1]]


Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.



In [98]:
m_15 = np.random.random((3, 3))

column_vector = np.zeros((3, 1))

for i, el in enumerate(m_15):
  column_vector[i, 0] = el.sum()

print(m_15, "\n")
print(column_vector)

[[0.37203962 0.54615189 0.55347802]
 [0.11984348 0.12181341 0.4502654 ]
 [0.24271323 0.41237722 0.00894841]] 

[[1.47166953]
 [0.69192229]
 [0.66403887]]


Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [104]:
print(f"matrix of numbers:\n{m_8}\n")

print(f"matrix of squares of numbers:\n{m_8 * m_8}")

matrix of numbers:
[[ 0  2  3  1]
 [ 5  1  5  3]
 [ 9  1 10  2]]

matrix of squares of numbers:
[[  0   4   9   1]
 [ 25   1  25   9]
 [ 81   1 100   4]]


Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [117]:
v_5 = np.random.randint(1, 51, size=(4))
print(v_5, "\n")

print(f"Square root:\n{np.sqrt(v_5)}")

[22 32 10 13] 

Square root:
[4.69041576 5.65685425 3.16227766 3.60555128]
